name: frameapp
description: "Embrace your creativity"
publish_to: 'none'
version: 0.0.5+26

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.5
  cached_network_image: ^3.4.1
  device_info_plus: ^11.5.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.0
  get_it: ^8.2.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  share_plus: ^11.1.0
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pin_input_text_field: ^4.5.2
  url_launcher: ^6.3.2

  sp_firebase:
    path: ../spaza/spaza-packages/sp-firebase
  sp_user_repository:
    path: ../spaza/spaza-packages/user-repository
  sp_utilities:
    path: ../spaza/spaza-packages/sp-utilities

dev_dependencies:
  flutter_lints: ^6.0.0

dependency_overrides:
  http: ^1.4.0
  intl: ^0.20.2
  timezone: ^0.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/pngs/
