// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGSvS7d2tuV7nK9xlxYH4klVKkmL6mpJ8',
    appId: '1:369506326548:web:b9154721c0eeef0373ef01',
    messagingSenderId: '369506326548',
    projectId: 'frame-7cff9',
    authDomain: 'frame-7cff9.firebaseapp.com',
    storageBucket: 'frame-7cff9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZtP9uZ_h6MJR9FGGutVuU8Dk7HQKitws',
    appId: '1:369506326548:android:94ef3a286dbcd91773ef01',
    messagingSenderId: '369506326548',
    projectId: 'frame-7cff9',
    storageBucket: 'frame-7cff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAierMTUWHwMzjKkSGNOmQxsPxzHZI0UKc',
    appId: '1:369506326548:ios:f2df8bf1f2f55dee73ef01',
    messagingSenderId: '369506326548',
    projectId: 'frame-7cff9',
    storageBucket: 'frame-7cff9.firebasestorage.app',
    iosBundleId: 'com.example.frameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAierMTUWHwMzjKkSGNOmQxsPxzHZI0UKc',
    appId: '1:369506326548:ios:f2df8bf1f2f55dee73ef01',
    messagingSenderId: '369506326548',
    projectId: 'frame-7cff9',
    storageBucket: 'frame-7cff9.firebasestorage.app',
    iosBundleId: 'com.example.frameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGSvS7d2tuV7nK9xlxYH4klVKkmL6mpJ8',
    appId: '1:369506326548:web:eed48a8c07462e0373ef01',
    messagingSenderId: '369506326548',
    projectId: 'frame-7cff9',
    authDomain: 'frame-7cff9.firebaseapp.com',
    storageBucket: 'frame-7cff9.firebasestorage.app',
  );
}
